### ISSUE TITLE
Extremely severe math error in question2.2.py and unnecessary usage of .strip()

### ISSUE THREAD

**Issue by SuketuPatni** [kry0sc0pic/cs-assignments#4]
You are summing up the series 
x + x^3/3! + x^5/5! + x^7/7! + x^9/9! ......
whereas what is asked is
x - x^3/3! + x^5/5! - x^7/7! + x^9/9! ......
You have totally forgotten to alternate the plus and minus signs, a grievous mistake.

Might I also add, the int() convertor has some stripping functionality of its own, so writing .strip() after input() in lines 33 and 34 is useless.

**Comment by kry0sc0pic** [comment]
ty for pointing it out.

here is a cookie 🍪
